# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(blank=True, max_length=20, null=True, verbose_name='商品ID')),
                ('imUrl', models.CharField(blank=True, max_length=200, null=True, verbose_name='商品图片链接')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='商品价格')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='商品标题')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
    ]
