# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='商品标题'),
        ),
    ]
